export const HISTORY_DAYS = 30;
export const HISTORY_MAP_LIMIT = 10000;
export const HISTORY_MAP_TARGET_POINTS = 3000;
export const HISTORY_REPORT_GPS_LIMIT = 20000;
export const HISTORY_EXPORT_GPS_LIMIT = 100000;
export const HISTORY_REPORT_TELEMETRY_BUCKET = '5s';
